version: '3'
services:
  halo:
    build: .
    network_mode: 'host'
    privileged: true
    environment:
        - THEARK_SERVER=http://10.4.1.10
        - THEARK_USER=admin
        - THEARK_PASS=password
        - THEARK_TYPE=CrowdControl
        - THEARK_UPSTREAM=http://cc.c2the.world
        - THEARK_REGISTER=False # Auto register the Halo if it doesnt exist