version: '3'
services:
  halo:
    build: .
    network_mode: 'host'
    privileged: true
    environment:
        # Halo settings
        - HALO_NAME=CrowdControl
        - HALO_UPSTREAM=http://cc.c2the.world
        # The number of IPs to use for this service
        - HALO_ADDR_COUNT=15

        # Ark settings
        - THEARK_SERVER=http://10.4.1.10
        - THEARK_USER=admin
        - THEARK_PASS=password
        - THEARK_REGISTER=False # Auto register the Halo if it doesnt exist